name: Artifact Image Deploy
on:
  workflow_dispatch:

env:
  GIT_OPS_REPOSITORY: ${ { env.GIT_OPS_REPOSITORY } }

jobs:
  artifact-build:
    name: Artifact Build and Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Artifact Build and Tests
        run: mvn clean install

  artifact-deploy:
    needs: artifact-build
    name: Artifact Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Docker Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Docker Image Tagging
        uses: PaulHatch/semantic-version@v4.0.2
        with:
          branch: main
          tag_prefix: 'v'
          major_pattern: 'release:'
          minor_pattern: 'feat:'
          format: "v${major}.${minor}.${patch}"

      - name: Docker Image Publish
        run: |
          docker build . --file Dockerfile --tag nutec/pace:latest --tag nutec/pace:${{ steps.versioning.outputs.version }} 
          docker push nutec/pace --all-tags 

  git-tagging:
    needs: artifact-deploy
    name: Git Tagging
    runs-on: ubuntu-latest
    steps:
      - name: Git tagging
        uses: actions/create-release@v1
        with:
          tag_name: ${{ steps.versioning.outputs.version }}
          release_name: ${{ steps.versioning.outputs.version }}

  artifact-image-version-update:
    needs: git-tagging
    name: Update Artifact Image Version
    runs-on: ubuntu-latest
    steps:
      - name: Update Artifact Image Version
        uses: passeidireto/trigger-external-workflow-action@main
        with:
          repository: $GIT_OPS_REPOSITORY
          event: update
          github_pat: ${{ secrets.GIT_OPS_TOKEN }}