name: Docker image publish
on:
  workflow_dispatch:

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}
  TAG_VERSION: $(date +%s)

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0    
        
      - name: Create jar file
        run: mvn clean install

      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}
          
      - name: Semantic versioning
        id: versioning
        uses: PaulHatch/semantic-version@v4.0.2
        with:
          branch: main
          tag_prefix: "v"
          major_pattern: "BREAKING CHANGE:"
          minor_pattern: "feat:"
          format: "v${major}.${minor}.${patch}"

      - name: Build and push docker image # Testando: BUREIKO CHENJARU TAIMU!!!!!
        run: |
          docker build . --file Dockerfile --tag oajojjj/pace:latest --tag oajojjj/pace:${{ steps.versioning.outputs.version }}
          docker push oajojjj/pace --all-tags
          
      - name: Git tagging 
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ steps.versioning.outputs.version }}
          release_name: ${{ steps.versioning.outputs.version }}
          body: |
            Changes in this Release
            - First Change
            - Second Change
          draft: false
          prerelease: false
      
      - name: Update image version on configuration github.repository
        uses: passeidireto/trigger-external-workflow-action@main
        env:
          PAYLOAD_TAG: ${{ steps.versioning.outputs.version }}
        with:
          repository: Lobato-s-Costa-s-company-ltd/tcc-back-config 
          event: update
          github_pat: ${{ secrets.REPOSITORY_TOKEN }}
         
